(() => {
  const single = (good, weak, near) => ({ options: [{ text: good, correct: true }, { text: weak[0], why: weak[1] }, { text: near[0], near: near[1] }] });
  const challenge = (id, prot, esc, opts) => ({ id, prot, esc, opts: opts.map((text, i) => ({ id: 'ABCD'[i], text, best: i === 0 })) });
  const questions = {
    atencion: ['Pedir que relate una atención en la que convirtió una necesidad en una recomendación memorable.', 'Preguntar si le gusta hablar con clientes.', 'Mide afinidad, no una práctica real.', 'Preguntar cuál es su producto favorito.', 'Es una buena apertura, pero no muestra cómo escucha ni recomienda.'],
    crecer: ['Pedir un reto nuevo que buscó y cómo sostuvo sus compromisos actuales.', 'Preguntar dónde se ve en cinco años.', 'Es demasiado general para detectar cómo crece hoy.', 'Preguntar si quiere crecer dentro de la compañía.', 'Muestra interés, pero no comportamiento.'],
    conexion: ['Pedir cómo hizo sentir parte a una persona nueva del equipo.', 'Preguntar si se considera sociable.', 'Una etiqueta no demuestra una acción concreta.', 'Preguntar qué valora de un buen equipo.', 'Aclara valores, no cómo construye vínculo.'],
    actitud: ['Pedir una jornada exigente y qué hizo para ayudar al equipo a avanzar.', 'Preguntar si siempre mantiene actitud positiva.', 'Invita una respuesta deseable, no evidencia.', 'Preguntar qué hace cuando tiene un mal día.', 'Aporta contexto, pero no impacto en otros.'],
    energia: ['Pedir cómo ajustó su ritmo para inspirar sin dejar atrás a una compañera.', 'Preguntar si tiene mucha energía.', 'Es una autopercepción sin situación observable.', 'Preguntar si disfruta trabajar bajo presión.', 'No muestra impacto positivo en el equipo.'],
    cumple: ['Pedir un compromiso que peligraba y cómo dio seguimiento hasta cerrarlo.', 'Preguntar si es una persona responsable.', 'La respuesta declarativa no verifica seguimiento.', 'Preguntar cómo organiza su agenda.', 'Es útil, pero no prueba cumplimiento.'],
    aprende: ['Pedir un feedback que convirtió en práctica concreta y qué cambió.', 'Preguntar si acepta bien las críticas.', 'No revela si transforma feedback en aprendizaje.', 'Preguntar cuál fue su último curso.', 'Habla de formación, no de mejora aplicada.'],
    rol: ['Pedir una decisión autónoma y cómo avisó a quienes necesitaban coordinarse.', 'Preguntar si prefiere trabajar sola.', 'Preferencia no equivale a autonomía responsable.', 'Preguntar qué tareas le gustan más.', 'No muestra cómo asume y conecta su rol.'],
    detalle: ['Pedir una corrección que convirtió en práctica guiada para otra persona.', 'Preguntar si es perfeccionista.', 'La etiqueta no muestra cómo protege el estándar.', 'Preguntar si detecta errores fácilmente.', 'Detectar no muestra cómo enseña sin presionar.'],
  };
  const PUZZLES = Object.fromEntries(Object.entries(questions).map(([id, q]) => [id, single(q[0], [q[1], q[2]], [q[3], q[4]])]));
  PUZZLES.experiencias = { multi: true, options: [
    { text: 'Pedir una situación en que anticipó una necesidad sin prometer algo imposible.', correct: true },
    { text: 'Preguntar cómo coordinó una alternativa cuando no tenía todos los recursos.', correct: true },
    { text: 'Preguntar si le gusta sorprender a las personas.', why: 'La intención no permite observar una experiencia sostenible.' },
  ] };

  window.CONTENT_ES = {
    ui: { language: '¿Ya está el equipo al completo?', welcomeIntro: 'Elegid el idioma de esta sesión.', start: 'Empezar', continue: 'Continuar', confirm: 'Confirmar', hire: 'Contratar', plan: 'Planificar su onboarding', interview: 'Empezar la entrevista', register: 'Registrar decisión', world: 'Ir al mundo real', next: 'Siguiente', resume: 'Reanudar', restart: 'Empezar de nuevo', sync: 'Sincronizar ahora', export: 'Exportar respaldo', offline: 'Sin conexión: las decisiones siguen guardadas en este dispositivo.', syncPending: 'Respaldo pendiente de sincronización.', syncDone: 'Registro enviado a la hoja.', timer: 'Tiempo restante', selected: 'elegidas', minimum: 'mínimo', deliberate: 'Deliberad antes de registrar vuestra decisión.', noAnswer: 'Sin respuesta' },
    welcome: { eyebrow: 'Store Manager Conference 2026', title: 'Una decisión compartida puede hacer florecer el talento.', premise: 'Sois un solo equipo. Conversad con las cartas físicas y registrad una decisión en cada momento.', rules: 'La duración máxima es de {duration} minutos. No gana quien termina primero: no hay puntos ni ganadores.', aliasLabel: 'Alias del equipo', aliasHelp: 'Usad un nombre breve para identificar vuestra mesa.' },
    acts: { act1: 'Acto 1 · La selección', act2: 'Acto 2 · El plan de onboarding', act3: 'Acto 3 · El mundo real' },
    req: { title: 'Definid el perfil', intro: 'Nos ponemos en situación: antes de entrevistar, elegid solo las competencias relevantes para este rol.', priorityTitle: 'Preparad la entrevista', priorityIntro: 'De las competencias elegidas, seleccionad las tres más importantes en orden de mayor a menor.' },
    interview: { single: '¿Cuál detecta de verdad? Descarta y quédate con una.', multi: 'Hay más de una que detecta. Marcad todas las que detecten.', success: 'Así se detecta.', missing: 'Casi. Falta al menos una.', weak: 'Esta opción no permite detectar la competencia.' },
    candidates: { title: 'Elegid a quién contratar', intro: 'Habéis preseleccionado a cuatro personas. Los perfiles ideales son difíciles de encontrar: elegid a una para acompañarla.', requirements: 'Requisitos', cv: 'CV', hired: 'Habéis contratado a {name}.', gaps: 'Estas son sus oportunidades de desarrollo:', noGaps: 'Cumple todos los requisitos; aun así, el acompañamiento intencional importa.' },
    onboarding: { rankTitle: 'Priorizad el onboarding', rankIntro: 'No vais a poder desarrollar todas las áreas a la vez. Tocad las dimensiones en orden: 1 es lo más importante y urgente.', focusTitle: 'Diseñad el enfoque', focusIntro: 'Elegid cómo acompañar esta dimensión.', revealTitle: 'Lo que conviene vigilar', revealIntro: 'Estos son los atajos que eligieron y el flanco que quedó descubierto.', intentional: 'Enfoque intencional', shortcut: 'Atajo', neglected: 'Flanco descubierto' },
    shadows: { title: 'Emergieron varias sombras', intro: '¿Cuál trabajáis primero?', fallback: 'La sombra dominante se hizo visible.' },
    case: { title: 'El caso', intro: 'La sombra que traía {name} se hizo visible. Conversad y registrad una decisión.' },
    close: { title: 'Lo construisteis vosotros', motto: 'Cada decisión puede hacer florecer el talento.', team: 'Equipo', candidate: 'Persona contratada', neglected: 'Flanco descuidado', decision: 'Decisión final' },
    REQS: ['Ganas de crecer', 'Crea conexiones genuinas', 'Actitud positiva ante los retos', 'Energía que inspira a clientes y equipo', 'Cumple lo que promete', 'Aprende y busca mejorar constantemente', 'Crea experiencias memorables', 'Se adueña de su rol', 'Cuida cada detalle'],
    POOL: [
      { id: 'atencion', block: 'Excelencia Comercial', w: 4, name: 'Atención al cliente y storytelling' }, { id: 'experiencias', block: 'Excelencia Comercial', w: 3, name: 'Crea experiencias memorables' }, { id: 'detalle', block: 'Excelencia Comercial', w: 3, name: 'Cuida cada detalle' },
      { id: 'conexion', block: 'Liderazgo y colaboración', w: 4, name: 'Crea conexiones genuinas' }, { id: 'actitud', block: 'Liderazgo y colaboración', w: 3, name: 'Actitud positiva ante los retos' }, { id: 'energia', block: 'Liderazgo y colaboración', w: 3, name: 'Energía que inspira a clientes y equipo' },
      { id: 'crecer', block: 'Desarrollo y autonomía', w: 4, name: 'Ganas de crecer' }, { id: 'aprende', block: 'Desarrollo y autonomía', w: 4, name: 'Aprende y busca mejorar constantemente' }, { id: 'cumple', block: 'Desarrollo y autonomía', w: 4, name: 'Cumple lo que promete' }, { id: 'rol', block: 'Desarrollo y autonomía', w: 3, name: 'Se adueña de su rol' },
      { id: 'lujo', block: 'Requisitos y Experiencia', w: 0, dist: true, name: 'Experiencia previa exclusiva en lujo' }, { id: 'idioma', block: 'Requisitos y Experiencia', w: 0, dist: true, name: 'Dominio avanzado de un tercer idioma' }, { id: 'titulo', block: 'Requisitos y Experiencia', w: 0, dist: true, name: 'Título universitario específico' },
    ],
    PUZZLES,
    CANDIDATES: [
      { id: 'valentina', name: 'Valentina', age: 26, tag: 'Iniciativa y aprendizaje', cv: 'Ha liderado activaciones comerciales y busca ampliar su impacto.', destaca: 'Avanza con energía y aprende rápido.', met: [true,true,true,true,false,true,true,false,true], shadows: ['crecer','energia'] },
      { id: 'sofia', name: 'Sofía', age: 29, tag: 'Vínculo y servicio', cv: 'Tiene experiencia creando confianza con clientes y equipos.', destaca: 'Hace que las personas se sientan vistas.', met: [true,true,false,true,true,true,true,true,false], shadows: ['conexion','actitud'] },
      { id: 'daniela', name: 'Daniela', age: 31, tag: 'Orden y resultados', cv: 'Ha sostenido operaciones exigentes con seguimiento consistente.', destaca: 'Convierte las promesas en hechos.', met: [false,true,true,false,true,true,false,true,true], shadows: ['cumple','detalle'] },
      { id: 'florencia', name: 'Florencia', age: 27, tag: 'Autonomía y estándar', cv: 'Destaca por tomar iniciativa y cuidar la calidad de cada entrega.', destaca: 'Protege el estándar y resuelve con autonomía.', met: [true,false,true,false,true,false,true,true,true], shadows: ['rol','detalle'] },
    ],
    DIMENSIONS: [
      { id: 'estandar', label: 'Estándar y expectativas', intencional: 'Acordar señales observables y revisarlas en contexto.', atajo: 'Explicar el estándar una vez y asumir que ya quedó claro.', mensaje: 'Informar no es lo mismo que dar claridad.' },
      { id: 'conexion', label: 'Conexión y pertenencia', intencional: 'Diseñar momentos de vínculo y contribución gradual.', atajo: 'Esperar a que la pertenencia aparezca sola.', mensaje: 'La pertenencia se construye con gestos repetidos.' },
      { id: 'conversaciones', label: 'Conversaciones y seguimiento', intencional: 'Agendar conversaciones breves con una prioridad y próximo paso.', atajo: 'Dejar el feedback para cuando haya un problema.', mensaje: 'La frecuencia convierte el feedback en orientación.' },
      { id: 'integracion', label: 'Integración y equidad', intencional: 'Hacer visibles los criterios y coordinar el acompañamiento.', atajo: 'Dar oportunidades sin explicar cómo ni por qué.', mensaje: 'La equidad hace visibles los criterios.' },
    ],
    SHADOW_MAP: { estandar: ['crecer','experiencias','detalle','cumple'], conexion: ['actitud'], conversaciones: ['conexion','aprende'], integracion: ['energia','rol'] },
    CHALLENGES: {
      crecer: challenge('crecer','Valentina','Destaca y ya pide un nuevo reto, pero deja a medias los acuerdos de su rol actual.',['Acompañarla a cerrar los compromisos actuales y acordar un reto gradual con revisión.','Dar el nuevo reto de inmediato para aprovechar su energía.','Pedirle que espere sin explicar cuándo podrá crecer.','Asignarle más tareas para comprobar si realmente puede.']),
      conexion: challenge('conexion','Sofía','Evita una conversación incómoda con una compañera para mantener el buen ambiente.',['Preparar una conversación privada, concreta y respetuosa sobre lo observado.','Hablar del tema con todo el equipo para que ella se dé por aludida.','Esperar a que la tensión se resuelva sola.','Pedir a otra persona que tenga la conversación por ella.']),
      actitud: challenge('actitud','Andrea','Anima al equipo tras una jornada difícil, pero no escucha una preocupación repetida.',['Reconocer la energía y abrir un espacio breve para entender la preocupación.','Repetir que mañana será un día mejor y seguir adelante.','Cambiar de tema para no bajar el ánimo.','Pedir que solo compartan soluciones ya terminadas.']),
      energia: challenge('energia','Lucía','Acelera el piso en hora punta y una asociada nueva empieza a cometer errores.',['Ajustar el ritmo, asignar apoyo puntual y revisar qué parte necesita práctica.','Mantener el ritmo para que aprenda bajo presión.','Retirarla de toda atención al cliente.','Corregir cada error delante del equipo.']),
      cumple: challenge('cumple','Daniela','Resuelve cada tarea, pero el equipo no entiende cómo prioriza cuando surgen imprevistos.',['Invitarla a compartir su criterio en una revisión breve de equipo.','Dejar que siga resolviendo porque sus resultados hablan por sí solos.','Asignarle solo tareas individuales para no distraerla.','Pedirle que documente todo sin conversar con nadie.']),
      aprende: challenge('aprende','Tomás','Pide feedback en cada turno y corrige tantas cosas a la vez que se frustra.',['Elegir un foco de práctica, reconocer avance y revisar después.','Dar feedback de todo para que avance más rápido.','Decirle que deje de preguntar hasta sentirse seguro.','Cambiarle de tarea cada día para que pruebe más cosas.']),
      experiencias: challenge('experiencias','Camila','Promete a una clienta una atención excepcional que depende de recursos que el equipo no tiene.',['Cuidar la relación, aclarar lo posible y coordinar una alternativa sostenible.','Cumplir la promesa aunque desordene al equipo.','Decir que no se puede sin ofrecer otra opción.','Pedir a otra tienda que resuelva siempre estas situaciones.']),
      rol: challenge('rol','Florencia','Toma decisiones con iniciativa, pero deja fuera a quienes necesitan coordinar con ella.',['Reconocer su iniciativa y acordar qué decisiones requieren consulta previa.','Pedirle que no tome ninguna decisión sola.','Dejar que el equipo se adapte a sus decisiones.','Asignarle una persona que decida todo por ella.']),
      detalle: challenge('detalle','Martina','Detecta cada error y corrige con precisión, pero la nueva asociada deja de preguntar.',['Convertir una corrección en práctica guiada, priorizando el detalle más importante.','Pedirle que sea todavía más estricta para mantener la calidad.','Evitar cualquier corrección hasta la siguiente evaluación.','Decir a la nueva asociada que debe ser más cuidadosa.']),
    },
  };
})();
